export default {
  MUTATION_SET_USER_TOKEN: "MUTATION_SET_USER_TOKEN",
  MUTATION_SET_USER: "MUTATION_SET_USER",
  ACTION_AUTHENTICATE: "ACTION_AUTHENTICATE",
  ACTION_FETCH_USER: "ACTION_FETCH_USER",
  ACTION_LOGOUT: "ACTION_LOGOUT",
  ACTION_UPDATEME: "ACTION_UPDATEME",
  ACTION_CHANGE_PASSWORD: "ACTION_CHANGE_PASSWORD"
};
